### Listagem de produtos
GET http://localhost:5292/api/produto/listar

### Cadastro de produtos
POST http://localhost:5292/api/produto/cadastrar
Content-Type: application/json

{
    "nome": "Lajota",
    "descricao": "Lisa",
    "quantidade" : 2,
    "preco": 14.00

}

### Buscar produto
GET http://localhost:5292/api/produto/buscar/e3731d35-450a-4038-958d-d2fc82197ff5
### Deletar Produto

### Remover um produto
DELETE http://localhost:5292/api/produto/remover
Content-Type: application/json

{
     "nome": "Tijola",
    "descricao": "6 furos",
    "preco": 7.00
}

###
PATCH http://localhost:5292/api/produto/alterar/0ad83007-28bb-4bb4-8747-467fd3e6db94
Content-Type: application/json

{
    "Nome": "Novo Nome",
    "Descricao": "Nova Descrição",
    "Preco": 10.99
}



# {
#     "nome": "Notebook Acer",
#     "descricao": "ACER Notebook Aspire 5 A515-56-32PG, Intel Core I3 11ª geração, 4GB, 256GB SDD, Windows11, Prata",
#     "preco": 2550

# }

# ### Alterar produto
# PATCH http://localhost:5292/api/produto/alterar
# Content-Type: application/json

# {
#     "id": 4,
#     "categoriaID": 2,
#     "nome": "Notebook Acer",
#     "descricao": "ACER Notebook Aspire 5 A515-56-32PG, Intel Core I3 11ª geração, 4GB, 256GB SDD, Windows11, Prata",
#     "preco": 2550

# }